# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialnet', '0002_auto_20161024_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='friend_requests',
            field=models.ManyToManyField(blank=True, related_name='_author_friend_requests_+', to='socialnet.Author'),
        ),
        migrations.AlterField(
            model_name='author',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='_author_friends_+', to='socialnet.Author'),
        ),
    ]
