# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 01:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialnet', '0005_auto_20161028_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=b'C:\\Users\\Gustavo\\Documents\\GitHub\\CMPUT404Project\\mysite\\static'),
        ),
    ]
