# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 19:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialnet', '0007_auto_20161030_1622'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='author',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=b'C:\\Users\\Gustavo\\Documents\\GitHub\\CMPUt404project\\mysite\\static'),
        ),
        migrations.AddField(
            model_name='requests',
            name='whoanswer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='who_answer', to='socialnet.Author'),
        ),
        migrations.AddField(
            model_name='requests',
            name='whosend',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='who_send', to='socialnet.Author'),
        ),
    ]
