# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 22:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialnet', '0008_auto_20161031_1459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requests',
            name='whoanswer',
        ),
        migrations.RemoveField(
            model_name='requests',
            name='whosend',
        ),
        migrations.DeleteModel(
            name='Requests',
        ),
    ]
