# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 14:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialnet', '0009_auto_20161031_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=b'C:\\Users\\Gustavo\\Documents\\GitHub\\cmput404project\\mysite\\static'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='socialnet.Post'),
        ),
    ]
