# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-03 21:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialnet', '0010_auto_20161101_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=b'/cshome/marcinko/Documents/C404/project/CMPUT404Project/static_cdn'),
        ),
    ]
