# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-17 03:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialnet', '0012_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='friend_requests',
        ),
        migrations.RemoveField(
            model_name='author',
            name='friends',
        ),
        migrations.AddField(
            model_name='author',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='_author_followers_+', to='socialnet.Author'),
        ),
        migrations.AddField(
            model_name='author',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='_author_following_+', to='socialnet.Author'),
        ),
        migrations.AlterField(
            model_name='author',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=b'/Users/edsonsilva/dev/CMPUT404Project/mysite/static_cdn'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=b''),
        ),
    ]
