# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-17 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialnet', '0014_auto_20161117_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='followers2', to='socialnet.Author'),
        ),
        migrations.AlterField(
            model_name='author',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='following2', to='socialnet.Author'),
        ),
    ]
