# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-20 23:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialnet', '0018_comment_pubdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='text',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='text',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='published_time',
            new_name='published',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='public',
            new_name='visibility',
        ),
        migrations.AddField(
            model_name='comment',
            name='content_type',
            field=models.CharField(choices=[('text/plain', 'text/plain'), ('text/markdown', 'text/markdown')], default='text/markdown', max_length=15),
        ),
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.CharField(default=None, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='host',
            field=models.URLField(default='http://127.0.0.1:8000/socialnet/'),
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.URLField(default=None),
        ),
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default=None, max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='author',
            name='avatar',
            field=models.URLField(default=None),
        ),
        migrations.AlterField(
            model_name='author',
            name='host',
            field=models.URLField(default='http://127.0.0.1:8000/socialnet/'),
        ),
    ]
