# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-20 23:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialnet', '0020_auto_20161120_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.CharField(default='description', max_length=40),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default='Title', max_length=40),
        ),
    ]
