# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-21 00:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialnet', '0022_auto_20161120_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='avatar',
            field=models.URLField(blank=True),
        ),
    ]
