# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-21 05:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialnet', '0027_auto_20161121_0452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='socialnet.Author'),
        ),
    ]
