# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-22 22:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialnet', '0029_auto_20161121_0543'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='displayname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
