# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-22 22:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialnet', '0030_author_displayname'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='url',
            field=models.URLField(default='http://127.0.0.1:8000/socialnet/'),
        ),
    ]
