# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-24 03:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialnet', '0031_author_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='displayname',
            new_name='displayName',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='content_type',
            new_name='contentType',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='content_type',
            new_name='contentType',
        ),
        migrations.RemoveField(
            model_name='post',
            name='host',
        ),
        migrations.AddField(
            model_name='post',
            name='origin',
            field=models.URLField(default='http://socialnets404.herokuapp.com/socialnet'),
        ),
        migrations.AddField(
            model_name='post',
            name='source',
            field=models.URLField(default='http://socialnets404.herokuapp.com/socialnet'),
        ),
        migrations.AlterField(
            model_name='author',
            name='host',
            field=models.URLField(default='http://127.0.0.1:8000/socialnet'),
        ),
        migrations.AlterField(
            model_name='author',
            name='url',
            field=models.URLField(default='http://127.0.0.1:8000/socialnet'),
        ),
    ]
