# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-24 04:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialnet', '0032_auto_20161124_0347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='visibility',
            field=models.CharField(default='PUBLIC', max_length=10),
        ),
    ]
