# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-26 22:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialnet', '0033_auto_20161124_0457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='host',
            field=models.URLField(default='http://socialnets404.herokuapp.com'),
        ),
        migrations.AlterField(
            model_name='author',
            name='url',
            field=models.URLField(default='http://socialnets404.herokuapp.com'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='contentType',
            field=models.CharField(choices=[('text/plain', 'text/plain'), ('text/x-markdown', 'text/x-markdown')], default='text/plain', max_length=15),
        ),
        migrations.AlterField(
            model_name='post',
            name='contentType',
            field=models.CharField(choices=[('text/plain', 'text/plain'), ('text/x-markdown', 'text/x-markdown')], default='text/plain', max_length=15),
        ),
        migrations.AlterField(
            model_name='post',
            name='origin',
            field=models.URLField(default='http://socialnets404.herokuapp.com'),
        ),
        migrations.AlterField(
            model_name='post',
            name='source',
            field=models.URLField(default='http://socialnets404.herokuapp.com'),
        ),
    ]
