# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-27 04:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialnet', '0034_auto_20161126_2201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='friends',
        ),
        migrations.AddField(
            model_name='author',
            name='authors',
            field=models.ManyToManyField(blank=True, related_name='_author_authors_+', to='socialnet.Author'),
        ),
    ]
