# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-27 06:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialnet', '0035_auto_20161127_0406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='host',
            field=models.URLField(default='http://socialnets404.herokuapp.com/'),
        ),
        migrations.AlterField(
            model_name='author',
            name='url',
            field=models.URLField(default='http://socialnets404.herokuapp.com/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='origin',
            field=models.URLField(default='http://socialnets404.herokuapp.com/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='source',
            field=models.URLField(default='http://socialnets404.herokuapp.com/'),
        ),
    ]
