# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-27 06:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('socialnet', '0036_auto_20161127_0601'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
