# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-27 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialnet', '0037_node_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='rcred_password',
            field=models.CharField(default='password123', max_length=255),
        ),
        migrations.AddField(
            model_name='node',
            name='rcred_username',
            field=models.CharField(default='admin', max_length=255),
        ),
    ]
