# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-27 08:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialnet', '0038_auto_20161127_0754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='access_to_images',
        ),
    ]
