# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-27 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialnet', '0039_remove_node_access_to_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
