# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-29 00:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialnet', '0040_author_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='pubdate',
            new_name='pubDate',
        ),
    ]
