# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-29 15:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialnet', '0041_auto_20161129_0000'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemoteComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=255)),
                ('post', models.URLField(blank=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialnet.Comment')),
            ],
        ),
    ]
