# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-29 15:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialnet', '0042_remotecomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remotecomment',
            name='comment',
        ),
        migrations.DeleteModel(
            name='RemoteComment',
        ),
    ]
